### ISSUE TITLE
Nitro emoji when sent, shows all ids for other instances of the same emoji

### ISSUE THREAD

**Issue by fabricioanciaes** [MitchWeaver/Discline#10]
This is a problem I'm facing when sending emojis. Nitro is set to true on discline config.

if a nitro emote has a single instance it works ok and looks like `<:emojiname:383332087224074240>`

now, if its an emoji that has the same name and is used across multiple servers (think of something popular, like a Kappa) it gets all the instances where this emote exists:

I type `:Kappa:` and it comes out `<<<<<<<<<:Kappa:330747890056167424>392693181092724737>231894438094307328>236168918736175106>263239549419913217>398559814340313100>286554931027116042>418978017730363393>336606916694245376>`

For some reason it returns 9 different ids for the Kappa emote.

My guess is that it should be getting only the first instance of kappa so this wont happen anymore. Trying with Kappa-1 or Kappa-2 does not work.

**Comment by mitchweaver** [comment]
Thanks for the report! This is a funny problem

Join the dev discord if you'd like to help, (I don't have nitro so hard to test 😛)
