### ISSUE TITLE
Use the term "guild" rather than "server" for consistency with the API

### ISSUE THREAD

**Issue by Martmists-GH** [MitchWeaver/Discline#11]

**Comment by mitchweaver** [comment]
Again, please provide a description when creating an issue / pull request.

Discord uses the term "server", not guild. 

If you search through the discord.py API [here](http://discordpy.readthedocs.io/en/latest/index.html), you'll notice "guild" isn't mentioned once.

Are you sure you're in the right place?

**Comment by Martmists-GH** [comment]
Discord.py definitely uses Guild, both in [source](https://github.com/Rapptz/discord.py/blob/rewrite/discord/guild.py) and [docs](http://discordpy.readthedocs.io/en/rewrite/api.html#guild)
Note that the `latest` branch is deprecated, and the `rewrite` branch is encouraged to be used.

**Comment by mitchweaver** [comment]
That is the documentation for discord.py rewrite, which we don't use

We're using the original discord.py, moving to the rewrite may happen in the future (particularly after the UI-rewrite)

**Comment by grimman** [comment]
Why would consistency with the API matter on the front end though? The official Discord UI uses "Server", while the API is what uses "Guild". Perhaps I'm misunderstanding the suggestion/issue, but if not, then front end should use front end terminology (it just seems reasonable!).

**Comment by mitchweaver** [comment]
Either way. *Should* we be using the rewrite, it may make sense to use their terminology, but it is confusing in its own right.

A better question is why the rewrite chose to use 'guild' and not 'server', being that that's what Discord uses.

**Comment by grimman** [comment]
The [Discord API](https://discordapp.com/developers/docs/resources/guild) uses the term Guild as well, so that's probably where it all stems from (presumably a legacy thing?). It's still not used on the front end, however, which is where the overwhelming majority of users live. To me it makes very little sense to mix back- and front-end terminology (though, to be fair, using inconsistent terminology to begin with also makes very little sense).

**Comment by Martmists-GH** [comment]
Why were all of these closed?

**Comment by mitchweaver** [comment]
rewrite is in progress, check pull requests
