### ISSUE TITLE
Pass instances around rather than globals

### ISSUE THREAD

**Issue by Martmists-GH** [MitchWeaver/Discline#15]
This is probably the worst implementation of a client I've seen, including having a global import `gc` which is used everywhere. Instead, for actions where `gc.*` is needed, it should be passed as argument rather than be imported.

See also: [StackOverflow - Why are global variables evil?](https://stackoverflow.com/a/19158418)

**Comment by mitchweaver** [comment]
It's going through a rewrite as we speak, just waiting on someone who is working on porting it to curses. 

It's not good code, it was slopped together quickly originally for a school assignment, I don't deny that. This project blew up a lot bigger than I thought it would, and like I said it's getting completely rewritten.

----

Just a side note, `This is probably the worst implementation of a client I've seen`. Not the best way to start an issue/PR.
