### ISSUE TITLE
In a recent update, Discord now hides tokens

### ISSUE THREAD

**Issue by BeehiveSystems** [MitchWeaver/Discline#29]
Discord's recent update now removed the token section from the dev console. I've looked around and couldn't find it. Has anyone figured out its new location?

**Comment by Danct12** [comment]
I found where to get the token, you just need to use web version of Discord.

**Comment by BeehiveSystems** [comment]
Can you include a screenshot? That's where I've been looking.

**Comment by Danct12** [comment]
![image](https://user-images.githubusercontent.com/19162768/43682706-a2ebec56-98a6-11e8-8bdb-b0637dae2670.png)

**Comment by BeehiveSystems** [comment]
That's very strange. Here's what I get on Firefox (same results with Chromium). 

https://i.imgur.com/trFIQSs.png

**Comment by Danct12** [comment]
That's really weird, it does exist for me and I even tried to click hard reload. Seems like I'm lucky.

**Comment by BeehiveSystems** [comment]
They might be rolling it out progressively. Seems like I'm not the only person affected by it.

https://www.reddit.com/r/discordapp/comments/9435e8/discord_wont_let_you_have_your_own_token/

**Comment by Danct12** [comment]
Seems like this is the end of an era for third party clients, hope it's not. Someone will still probably be able to get the token using another way. I already got my token so I'm safe, but I fear that the token will change sometime in the future.

**Comment by idontknowanyoneonhere** [comment]
I've lost the token in the dev controls too but if i have it open and reload discord (in a browser obviously, can be regular or hard reload) my token pops up there for a few seconds while the page loads and then it disappears again, it stays there long enough for me to copy it.

**Comment by BeehiveSystems** [comment]
According to a Discord dev in another thread (no link, saw it earlier today), the tokens aren't being refreshed. They will only change if the user changes their password.

**Comment by BeehiveSystems** [comment]
@jibreil Brilliant workaround. I was able to grab my token! Thank you.

**Comment by Danct12** [comment]
If you have top-tier internet that loads Discord like sanic, just reload and while its loading try to yank the ethernet cable (will not be responsible for broken cords) or turn off the internet :P

**Comment by Danct12** [comment]
Also my Discord token changed after I added mobile number 2 way authentication I think, it took me a few days to figured out that the token was changed.

**Comment by idontknowanyoneonhere** [comment]
Here's a gif of me grabbing the token of a sacrificial account

![](https://thumbs.gfycat.com/IgnorantGreenEmperorpenguin-size_restricted.gif)

You can see the token appear briefly on the right as the page loads.

**Comment by BeehiveSystems** [comment]
Thanks for photos. I'll go ahead and close the issue, this should be more than enough for anyone stumbling upon this in the future.
