### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1,

### ISSUE THREAD

**Issue by Merith-TK** [MitchWeaver/Discline#30]
I try to install the program with
`pip install asyncio discord blessings pyyaml`
ANd i get an error

>zd-server@Zach-Server:~/git/discord-cli$ pip install asyncio discord blessings pyyaml
Collecting asyncio
  Downloading https://files.pythonhosted.org/packages/da/54/054bafaf2c0fb8473d423743e191fcdf49b2c1fd5e9af3524efbe097bafd/asyncio-3.4.3.tar.gz (204kB)
    100% |████████████████████████████████| 204kB 867kB/s 
Collecting discord
  Downloading https://files.pythonhosted.org/packages/7d/d2/7424dcf9c008623961acf996a3476e692752bb23b553eb28a668beee4136/discord-0.0.2.tar.gz
Collecting blessings
  Downloading https://files.pythonhosted.org/packages/8d/b1/a3fe6fd8a012e6d019bafd671c2fee0597ea97ff2e76c25aadfa4545fc32/blessings-1.7-py2-none-any.whl
Collecting pyyaml
  Downloading https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz (270kB)
    100% |████████████████████████████████| 276kB 1.2MB/s 
Collecting discord.py (from discord)
  Downloading https://files.pythonhosted.org/packages/97/3c/2a97b47fd8839f8863241857bbd6a3998d1de1662b788c8d9322e5a40901/discord.py-0.16.12.tar.gz (414kB)
    100% |████████████████████████████████| 419kB 1.3MB/s 
Collecting six (from blessings)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting aiohttp<1.1.0,>=1.0.0 (from discord.py->discord)
  Downloading https://files.pythonhosted.org/packages/09/5a/7b81ea8729d41f44c6fe6a116e466c8fb884950a0061aa3768dbd6bee2f8/aiohttp-1.0.5.tar.gz (499kB)
    100% |████████████████████████████████| 501kB 862kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Enxe4C/aiohttp/setup.py", line 60, in <module>
        raise RuntimeError("aiohttp requires Python 3.4.2+")
    RuntimeError: aiohttp requires Python 3.4.2+
    
>    ----------------------------------------
>Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Enxe4C/aiohttp/

___

When i check my python versions, this is what i get
>root@Zach-Server:~/git/discord-cli# apt install python
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python is already the newest version (2.7.15~rc1-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@Zach-Server:~/git/discord-cli# apt install python3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3 is already the newest version (3.6.5-3ubuntu1).
>0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by mitchweaver** [comment]
My guesses:

1. you may have two versions of pip, `pip` and `pip3` use pip3
2. You may have two versions of python3, an earlier version, and the 3.6.5 stated. Make sure pip3 is using the 3.6.5 version
