### ISSUE TITLE
Description for getting token is deprecated

### ISSUE THREAD

**Issue by kimusan** [MitchWeaver/Discline#33]
The token have been moved from local store. It can not be found using this description https://discordhelp.net/discord-token

**Comment by mitchweaver** [comment]
Yes, and this is unfortunate. Still waiting for a good workaround.

It seems this is Discord making it clear they are against clients like us, and they are in the position of ultimate power.

-----

*note:* if you have already gotten your token before this update, it will stlil function as normal

**Comment by kimusan** [comment]
The method in the link is easy and works well

**Comment by queercat** [comment]
The link is a fantastic method to get the token, you can also still get it from local store with a bit of finnicky ness.
