### ISSUE TITLE
Token importation not working

### ISSUE THREAD

**Issue by lorcroce** [MitchWeaver/Discline#44]
Following the installation guide I ran (with python 3.6.7) :

`python3 Discline.py --store-token`

I'm getting this error :

```
Traceback (most recent call last):
  File "Discline.py", line 27, in <module>
    from client.serverlog import ServerLog
  File "/home/Discline/client/serverlog.py", line 1, in <module>
    from discord import Server, Channel
ImportError: cannot import name 'Server'
```

**Comment by Myeloon** [comment]
Are you on python 3.7? If so, use 3.6 or older and try again

**Comment by ShinyNewLove** [comment]
Also getting this error in Python 3.7

**Comment by THEWHITEBOY503** [comment]
I'm also getting this issue.

**Comment by q-TheDog** [comment]
> Also getting this error in Python 3.7

python 3.7 won't work. That being said, I'm using 3.6.8 and getting the same error as Beau

**Comment by q-TheDog** [comment]
Well, I got it to work, but I had to downgrade a few packages quite a bit:
```
sudo python3.6 -m pip install async_timeout==2.0.1 aiohttp==1.0.0 discord==0.16.12
```

Let me know if there's any way to get this working with newer versions of these.

**Comment by humboldt123** [comment]
I got this error too.

**Comment by ghost** [comment]
Any update on the issue?
