### ISSUE TITLE
How to store token with mfa enabled

### ISSUE THREAD

**Issue by s3cpat** [MitchWeaver/Discline#54]
```
Checking for updates...



Starting...

# and it just hangs...
```

I use 2FA with my Discord account.  I retrieved my token from Discord using the chrome developer console method.  It is prefixed by "`mfa.`".  Discline does not reject this token, but it does hang when starting.  Thoughts?

**Comment by Danct12** [comment]
If you're in many guilds, it'll take a long time to login.
Also this repo hasn't updated for a year now, try use this fork.
https://github.com/NatTupper/dline

Vào Th 3, 19 thg 2, 2019 vào lúc 04:54 s3cpat <notifications@github.com>
đã viết:

**Comment by s3cpat** [comment]
Thanks!
