### ISSUE TITLE
Switching channels / servers is clunky and inefficient

### ISSUE THREAD

**Issue by SkyLeite** [MitchWeaver/Discline#8]
Discline is a great software and I'm honestly surprised by how well it works, considering I've tried writing something like it myself. However, there are some problems with usability that I'd like to address, mainly channel / server switching.

The whole point of terminal clients, the way I see it, is to make them fully usable with a keyboard only, as taking your hands off them to use the mouse is incredibly inefficient. However, the way you switch channels / servers in Discline at the moment manages to somehow be even more inefficient than using the mouse on the official client. You have to:

1. Type `/servers` to see the list of servers
2. Find the server you want to switch to
3. Press `q`
4. Type `/server servername`

That's four steps for something as simple as checking for messages on another server. The good news, however, is that this problem has already been solved. Vim has an extension called Ctrlp that's used to switch files seamlessly. Here's how you do it:

1. Press Ctrl + P. This opens a tiny box with a list of files.
2. Type (part of) the name of the file you want to switch to (it uses fuzzy searching)
3. Press enter.

Alternatively you can use the arrow keys to highlight the file, but that's slow. I feel like Discline could benefit greatly from something like this, as even the official client already has something like this (Ctrl + K) and it works wonders.

**Comment by mitchweaver** [comment]
They all auto-complete, you can just type `/c s`, for example to expand to `/channel Some Named Channel`.

For example, I am in the /r/unixporn server, so if I want to switch to it, I type `/s u`.

Not so hard, is it?

There is also `/c` with indexes, for example, to change to the first channel in a server, you can type `/c1`. 
The 2nd, `/c2`, and so on. This can be configured to start at 0 if you wish.

Once we move to curses we'll have more freedom for keybinding.

**Comment by mitchweaver** [comment]
Closing this for now as it serves no purpose, however keybinding and a UI revamped are coming soon.
